---
#==============================================================================
# EXAMPLE USER ENTITY
#==============================================================================

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
#==============================================================================
# EXAMPLE GROUP ENTITY
#==============================================================================

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
